/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Prestador;

import P.I.TelaEditarClientes;

/**
 *
 * @author Luis Henrique Gianet
 */
public class HomePrestador extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public HomePrestador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Chat6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Chat7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Chat8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Chat9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Chat10 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Chat11 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        Chat12 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Chat13 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        Chat14 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        Chat15 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        Chat16 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        Chat17 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon.png"))); // NOI18N
        jLabel17.setText("jLabel1");

        Chat6.setBackground(new java.awt.Color(0, 0, 102));
        Chat6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat6.setForeground(new java.awt.Color(255, 255, 255));
        Chat6.setText("Chat");
        Chat6.setBorder(null);
        Chat6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat6ActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_2.png"))); // NOI18N
        jLabel18.setText("jLabel1");

        Chat7.setBackground(new java.awt.Color(0, 0, 102));
        Chat7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat7.setForeground(new java.awt.Color(255, 255, 255));
        Chat7.setText("Tarefas");
        Chat7.setBorder(null);
        Chat7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat7ActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_2.png"))); // NOI18N
        jLabel19.setText("jLabel1");

        Chat8.setBackground(new java.awt.Color(0, 0, 102));
        Chat8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat8.setForeground(new java.awt.Color(255, 255, 255));
        Chat8.setText("Configuração");
        Chat8.setBorder(null);
        Chat8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat8ActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4115235-exit-logout-sign-out_114030 (1).png"))); // NOI18N
        jLabel20.setText("jLabel1");

        Chat9.setBackground(new java.awt.Color(0, 0, 102));
        Chat9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat9.setForeground(new java.awt.Color(255, 255, 255));
        Chat9.setText("Sair");
        Chat9.setBorder(null);
        Chat9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat9ActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_32x32.png"))); // NOI18N
        jLabel21.setText("jLabel1");

        Chat10.setBackground(new java.awt.Color(0, 0, 102));
        Chat10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat10.setForeground(new java.awt.Color(255, 255, 255));
        Chat10.setText("Ajuda ?");
        Chat10.setBorder(null);
        Chat10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat10ActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-homem-com-círculo-32.png"))); // NOI18N
        jLabel22.setText("jLabel1");

        Chat11.setBackground(new java.awt.Color(0, 0, 102));
        Chat11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat11.setForeground(new java.awt.Color(255, 255, 255));
        Chat11.setText("Perfil");
        Chat11.setBorder(null);
        Chat11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat11ActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/work_manager_resized_800x800.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chat11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chat10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Chat9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chat8))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chat7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chat6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel23)
                .addGap(58, 58, 58)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(Chat6))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(Chat7))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(Chat8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(Chat11))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(Chat10))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(Chat9))
                .addGap(256, 256, 256))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 102));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon.png"))); // NOI18N
        jLabel28.setText("jLabel1");

        Chat12.setBackground(new java.awt.Color(0, 0, 102));
        Chat12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat12.setForeground(new java.awt.Color(255, 255, 255));
        Chat12.setText("Chat");
        Chat12.setBorder(null);
        Chat12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat12ActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_2.png"))); // NOI18N
        jLabel29.setText("jLabel1");

        Chat13.setBackground(new java.awt.Color(0, 0, 102));
        Chat13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat13.setForeground(new java.awt.Color(255, 255, 255));
        Chat13.setText("Tarefas");
        Chat13.setBorder(null);
        Chat13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat13ActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_2.png"))); // NOI18N
        jLabel30.setText("jLabel1");

        Chat14.setBackground(new java.awt.Color(0, 0, 102));
        Chat14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat14.setForeground(new java.awt.Color(255, 255, 255));
        Chat14.setText("Configuração");
        Chat14.setBorder(null);
        Chat14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat14ActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4115235-exit-logout-sign-out_114030 (1).png"))); // NOI18N
        jLabel31.setText("jLabel1");

        Chat15.setBackground(new java.awt.Color(0, 0, 102));
        Chat15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat15.setForeground(new java.awt.Color(255, 255, 255));
        Chat15.setText("Sair");
        Chat15.setBorder(null);
        Chat15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat15ActionPerformed(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_32x32.png"))); // NOI18N
        jLabel32.setText("jLabel1");

        Chat16.setBackground(new java.awt.Color(0, 0, 102));
        Chat16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat16.setForeground(new java.awt.Color(255, 255, 255));
        Chat16.setText("Ajuda ?");
        Chat16.setBorder(null);
        Chat16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat16ActionPerformed(evt);
            }
        });

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-homem-com-círculo-32.png"))); // NOI18N
        jLabel33.setText("jLabel1");

        Chat17.setBackground(new java.awt.Color(0, 0, 102));
        Chat17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat17.setForeground(new java.awt.Color(255, 255, 255));
        Chat17.setText("Perfil");
        Chat17.setBorder(null);
        Chat17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat17ActionPerformed(evt);
            }
        });

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/work_manager_resized_800x800.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chat17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chat16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Chat15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chat14))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chat13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chat12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel34)
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(Chat12))
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(Chat13))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(Chat14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33)
                    .addComponent(Chat17))
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(Chat16))
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(Chat15))
                .addGap(256, 256, 256))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel9.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 250, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 250, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Banco itau");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 86, -1));

        jLabel9.setText("menor aprendiz");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 135, -1));

        jButton1.setText("Sobre a vaga");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButton2.setText("Enviar Corrículo");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 43, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 43, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 43, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 43, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 43, -1));

        jLabel24.setText("Nome:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel25.setText("Profição Requirida:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setText("Banco itau");
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 86, -1));

        jLabel51.setText("menor aprendiz");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 135, -1));

        jButton7.setText("Sobre a vaga");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton8.setText("Corrículo");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel13.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 43, -1));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel13.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 43, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel13.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 43, -1));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel13.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 43, -1));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel13.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 43, -1));

        jLabel64.setText("Nome:");
        jPanel13.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel65.setText("Profição Requirida:");
        jPanel13.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 250, 270));

        jLabel66.setText("Hora:");
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel67.setText("Mês:");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel68.setText("R$ 5,00");
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, -1));

        jLabel69.setText(" R$ 2000,00");
        jPanel4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 121, -1));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 250, 270));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setText("Banco itau");
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 86, -1));

        jLabel36.setText("menor aprendiz");
        jPanel10.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 135, -1));

        jLabel37.setText("R$ 5,00");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, -1));

        jLabel38.setText(" R$ 2000,00");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 121, -1));

        jButton3.setText("Sobre a vaga");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 43, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 43, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 43, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 43, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 43, -1));

        jLabel44.setText("Nome:");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel45.setText("Profição Requirida:");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        jLabel46.setText("Hora:");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel47.setText("Mês:");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jButton11.setText("Enviar Corrículo");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 250, 270));

        jPanel11.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 230, 250, -1));

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setText("Banco itau");
        jPanel12.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 86, -1));

        jLabel49.setText("menor aprendiz");
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 135, -1));

        jButton5.setText("Sobre a vaga");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel12.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 43, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel12.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 43, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel12.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 43, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel12.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 43, -1));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel12.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 43, -1));

        jLabel57.setText("Nome:");
        jPanel12.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel58.setText("Profição Requirida:");
        jPanel12.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        jPanel14.setBackground(new java.awt.Color(102, 102, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setText("Banco itau");
        jPanel14.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 86, -1));

        jLabel71.setText("menor aprendiz");
        jPanel14.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 135, -1));

        jButton9.setText("Sobre a vaga");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton10.setText("Corrículo");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel14.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 43, -1));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel14.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 43, -1));

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel14.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 43, -1));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel14.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 43, -1));

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel14.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 43, -1));

        jLabel77.setText("Nome:");
        jPanel14.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel78.setText("Profição Requirida:");
        jPanel14.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 250, 270));

        jLabel79.setText("Hora:");
        jPanel12.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel80.setText("Mês:");
        jPanel12.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel81.setText("R$ 5,00");
        jPanel12.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, -1));

        jLabel82.setText(" R$ 2000,00");
        jPanel12.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 121, -1));

        jButton4.setText("Enviar Corrículo");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 250, 270));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1930, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1930, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Chat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat6ActionPerformed

    private void Chat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat7ActionPerformed

    private void Chat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat8ActionPerformed

    private void Chat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat9ActionPerformed
        LoginPrestadores objpres = new LoginPrestadores();
        objpres.setVisible(true);
        dispose();
     }//GEN-LAST:event_Chat9ActionPerformed

    private void Chat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat10ActionPerformed

    private void Chat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Chat17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat17ActionPerformed

    private void Chat16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat16ActionPerformed

    private void Chat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat15ActionPerformed

    private void Chat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat14ActionPerformed

    private void Chat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat13ActionPerformed

    private void Chat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePrestador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chat10;
    private javax.swing.JButton Chat11;
    private javax.swing.JButton Chat12;
    private javax.swing.JButton Chat13;
    private javax.swing.JButton Chat14;
    private javax.swing.JButton Chat15;
    private javax.swing.JButton Chat16;
    private javax.swing.JButton Chat17;
    private javax.swing.JButton Chat6;
    private javax.swing.JButton Chat7;
    private javax.swing.JButton Chat8;
    private javax.swing.JButton Chat9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
