/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package P.I;

import Prestador.HomePrestador;
import Prestador.LoginPrestadores;

/**
 *
 * @author Luis Henrique Gianet
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Chat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Chat1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Chat2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Chat3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Chat4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        perfil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Chat5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 206, 37, -1));

        Chat.setBackground(new java.awt.Color(0, 0, 102));
        Chat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat.setForeground(new java.awt.Color(255, 255, 255));
        Chat.setText("Chat");
        Chat.setBorder(null);
        Chat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatActionPerformed(evt);
            }
        });
        jPanel2.add(Chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 213, 66, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/savetheapplication_guardar_2958.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 269, 37, -1));

        Chat1.setBackground(new java.awt.Color(0, 0, 102));
        Chat1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat1.setForeground(new java.awt.Color(255, 255, 255));
        Chat1.setText("Salvos");
        Chat1.setBorder(null);
        Chat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat1ActionPerformed(evt);
            }
        });
        jPanel2.add(Chat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 276, 66, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_2.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 335, 37, -1));

        Chat2.setBackground(new java.awt.Color(0, 0, 102));
        Chat2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat2.setForeground(new java.awt.Color(255, 255, 255));
        Chat2.setText("Configuração");
        Chat2.setBorder(null);
        Chat2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat2ActionPerformed(evt);
            }
        });
        jPanel2.add(Chat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 342, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4115235-exit-logout-sign-out_114030 (1).png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 792, 37, -1));

        Chat3.setBackground(new java.awt.Color(0, 0, 102));
        Chat3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat3.setForeground(new java.awt.Color(255, 255, 255));
        Chat3.setText("Sair");
        Chat3.setBorder(null);
        Chat3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat3ActionPerformed(evt);
            }
        });
        jPanel2.add(Chat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 799, 57, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/white_icon_32x32.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 722, 37, -1));

        Chat4.setBackground(new java.awt.Color(0, 0, 102));
        Chat4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat4.setForeground(new java.awt.Color(255, 255, 255));
        Chat4.setText("Ajuda ?");
        Chat4.setBorder(null);
        Chat4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat4ActionPerformed(evt);
            }
        });
        jPanel2.add(Chat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 729, 77, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-homem-com-círculo-32.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 657, 37, -1));

        perfil.setBackground(new java.awt.Color(0, 0, 102));
        perfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        perfil.setForeground(new java.awt.Color(255, 255, 255));
        perfil.setText("Perfil");
        perfil.setBorder(null);
        perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        jPanel2.add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 664, 71, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/work_manager_resized_800x800.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 48, 112, -1));

        Chat5.setBackground(new java.awt.Color(0, 0, 102));
        Chat5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Chat5.setForeground(new java.awt.Color(255, 255, 255));
        Chat5.setText("Prestador");
        Chat5.setBorder(null);
        Chat5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat5ActionPerformed(evt);
            }
        });
        jPanel2.add(Chat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 110, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-homem-com-círculo-32.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 250, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("João roberto");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 86, -1));

        jLabel9.setText("Engenheiro de obras");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 135, -1));

        jLabel10.setText("Hora R$ 45,00");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, -1));

        jLabel11.setText("Mês: R$ 2000,00");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 121, -1));

        jButton1.setText("Sobre min");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton2.setText("Contratar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 43, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 43, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 43, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 43, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 43, -1));

        jLabel18.setText("Nome:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel19.setText("Profição:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel20.setText("Preço:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel21.setText("Preço:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 250, 270));

        jPanel16.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, 250, 140));

        jPanel15.setBackground(new java.awt.Color(102, 102, 102));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setText("João roberto");
        jPanel15.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 86, -1));

        jLabel61.setText("Engenheiro de obras");
        jPanel15.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 135, -1));

        jLabel62.setText("Hora R$ 45,00");
        jPanel15.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, -1));

        jLabel63.setText("Mês: R$ 2000,00");
        jPanel15.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 121, -1));

        jButton13.setText("Sobre min");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jButton14.setText("Contratar");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel15.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 43, -1));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel15.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 43, -1));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel15.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 43, -1));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel15.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 43, -1));

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel15.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 43, -1));

        jLabel26.setText("Nome:");
        jPanel15.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel27.setText("Profição:");
        jPanel15.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel28.setText("Preço:");
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel29.setText("Preço:");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 440, 250, 260));

        jPanel12.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, 140));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setText("João roberto");
        jPanel11.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 86, -1));

        jLabel43.setText("Engenheiro de obras");
        jPanel11.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 135, -1));

        jLabel44.setText("Hora R$ 45,00");
        jPanel11.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, -1));

        jLabel45.setText("Mês: R$ 2000,00");
        jPanel11.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 121, -1));

        jButton7.setText("Sobre min");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton8.setText("Contratar");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel11.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 43, -1));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel11.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 43, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel11.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 43, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ffff.png"))); // NOI18N
        jPanel11.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 43, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stars_star_favourite_icon_149374.png"))); // NOI18N
        jPanel11.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 43, -1));

        jLabel22.setText("Nome:");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel23.setText("Profição:");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel24.setText("Preço:");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel25.setText("Preço:");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 250, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChatActionPerformed

    private void Chat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat1ActionPerformed

    private void Chat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat2ActionPerformed

    private void Chat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat3ActionPerformed
        Login objcli = new Login();
        objcli.setVisible(true);
        dispose();
    }//GEN-LAST:event_Chat3ActionPerformed

    private void Chat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chat4ActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
       TelaEditarClientes objcli = new TelaEditarClientes();
        objcli.setVisible(true);
        dispose();
    }//GEN-LAST:event_perfilActionPerformed

    private void Chat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat5ActionPerformed
        LoginPrestadores objcli = new LoginPrestadores();
        objcli.setVisible(true);
        dispose();

    }//GEN-LAST:event_Chat5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chat;
    private javax.swing.JButton Chat1;
    private javax.swing.JButton Chat2;
    private javax.swing.JButton Chat3;
    private javax.swing.JButton Chat4;
    private javax.swing.JButton Chat5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton perfil;
    // End of variables declaration//GEN-END:variables
}
